-- Anime Mood Supabase schema
-- Run this in Supabase SQL Editor when you are ready to enable cross-device accounts.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  favorite_anime text[] default '{}',
  favorite_genres text[] default '{}',
  avoided_genres text[] default '{}',
  preferred_pacing text default 'any',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.anime_library (
  id bigint primary key,
  title text not null,
  title_english text,
  type text,
  status text,
  episodes integer,
  score numeric,
  popularity integer,
  synopsis text,
  genres text[] default '{}',
  themes text[] default '{}',
  image_url text,
  trailer_url text,
  updated_at timestamptz default now()
);

create table if not exists public.user_anime (
  user_id uuid references auth.users(id) on delete cascade,
  anime_id bigint references public.anime_library(id) on delete cascade,
  status text not null check (status in ('watching','completed','plan','dropped')),
  rating integer check (rating between 1 and 10),
  updated_at timestamptz default now(),
  primary key (user_id, anime_id)
);

create table if not exists public.recommendation_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  anime_id bigint,
  feedback text not null,
  reasons text[] default '{}',
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;
alter table public.user_anime enable row level security;
alter table public.recommendation_feedback enable row level security;

create policy "profiles own row" on public.profiles for all using (auth.uid()=id) with check (auth.uid()=id);
create policy "user anime own rows" on public.user_anime for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "feedback own rows" on public.recommendation_feedback for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
